### ISSUE TITLE
Possibility of adding team name text to jerseys

### ISSUE THREAD

**Issue by tomkennedy22** [zengm-games/facesjs#26]
I've played around with the concept of adding in team names to jerseys, if a team has that feature enabled.  It would require some changes for the display function to (A) determine if this team displays team name, and (B) actually pull the team name in. But the text can be added as a simple SVG element. 

No worries if you're not interested, but I have some of the code to display working now, and could finish it up if the feature is appealing. 

<img width="307" alt="Screen Shot 2022-09-04 at 5 28 53 PM" src="https://user-images.githubusercontent.com/5054058/188336049-4cf6f9b7-bdf3-4bfb-bc2c-18a347fb8ab8.png">
<img width="202" alt="Screen Shot 2022-09-04 at 5 29 13 PM" src="https://user-images.githubusercontent.com/5054058/188336055-3b9dca59-aece-4ad8-8cfa-55a5762bfefd.png">
<img width="219" alt="Screen Shot 2022-09-04 at 5 29 30 PM" src="https://user-images.githubusercontent.com/5054058/188336057-d2218fcf-62a8-4581-a80d-31cbc0a9a1ef.png">
<img width="220" alt="Screen Shot 2022-09-04 at 5 29 54 PM" src="https://user-images.githubusercontent.com/5054058/188336059-2080de70-a407-4bf3-bba4-d6cfa681bd31.png">

**Comment by dumbmatter** [comment]
Thanks, it's a cool idea! But I think the text is too small with the space you have available now. And making the images taller to allow more space is probably not worth it. So I think I am going to pass on this one.
