### ISSUE TITLE
Thoughts on a gallery for feature selection?

### ISSUE THREAD

**Issue by tomkennedy22** [zengm-games/facesjs#31]
When I build a custom face, sometimes I have trouble remembering what all the hair, mouth, eye options are. I thought that maybe a gallery of sorts, where you take you existing face, and then look at all X options (hair, accessory, etc), and choose which you like the most

I have a **very very very rough draft** below, but option for any thoughts on:

1. Is it a good idea at all
2. How to make it look good
3. How it should act
4. Should it be a standalone page? Or just in editor.html
5. Eh, any other thoughts are welcome!

https://github.com/tomkennedy22/facesjs/pull/5

https://github.com/zengm-games/facesjs/assets/5054058/7269ed45-5e1b-4ca4-8abe-8114c0b389ed

**Comment by dumbmatter** [comment]
The problem with adding so many features to editor.html is that at some point it'd probably make sense to use a JS framework, it gets hard to manage everything in vanilla JS. But is this that point? idk, this might still be okay. But at some point, it's all going to get too confusing.

This is a really cool feature. Maybe you could make the faces clickable, so clicking one closes the gallery and selects that feature for the main face. And hide the textarea and buttons below it while the gallery is open.

**Comment by tomkennedy22** [comment]
This idea evolved into #35. Gonna close
