### ISSUE TITLE
React is needed to be able to generate faces

### ISSUE THREAD

**Issue by Yasso9** [zengm-games/facesjs#51]
I have a vue.js project and to be able to use this library I need to have React installed.

Here is the code that I use in my project :

```
import { generate } from "facesjs";
const face = generate()
```

If React is not installed, I have the following error, even if I did not import explicitly face: 

```
[1]  ERROR  [worker reload] [worker init] error: Cannot find package "react" from "node_modules/facesjs/build/esmodules/Face.js"
```

**Comment by dumbmatter** [comment]
My bad, I guess I was thinking that tree shaking would get rid of the react component if it wasn't being used, but that is definitely not always true. Will try to fix this later today.

**Comment by dumbmatter** [comment]
Also in the mean time if you downgrade to version 4.1.1 it should work.

**Comment by Yasso9** [comment]
Thanks a lot for your quick answer and the workaround !

**Comment by dumbmatter** [comment]
Fixed in version 4.2.2

**Comment by gpronet** [comment]
Probably something related to this change (or me doing something wrong), but when building the module, the file Face.js is not being generated. As a result the Face component won't work when imported into a React project.

I can see all other files are properly generated in \build\esmodules, only Face.js is missing. No errors occur during the build process.

**Comment by gpronet** [comment]
The missing Face.js seems to be related to building the module on a Windows machine. When I build it on MacOS, everything works fine.

**Comment by dumbmatter** [comment]
Interesting, I wonder if it's somehow due to the capital letter in the filename? Although faceToSvgString.js is also mixed case, but not as the first letter. I don't have a Windows machine right now so I can't debug. PR welcome if you figure it out!
